conda-forge/mss-feedstock

- .gitattributes
- .travis.yml
- README.md
- appveyor.yml
- ci_support/run_docker_build.sh
- recipe/meta.yaml
Re-render and removed the `icu` pin.
> Update icu pin

- recipe/meta.yaml
Checklist
* [X ] Used a fork of the feedstock to propose changes
> version 1.7.2

- .ci_support/linux_python2.7.yaml
- .ci_support/linux_python3.5.yaml
- .ci_support/linux_python3.6.yaml
- .ci_support/osx_python2.7.yaml
- .ci_support/osx_python3.5.yaml
- .ci_support/osx_python3.6.yaml
- .ci_support/win_python2.7.yaml
- .ci_support/win_python3.5.yaml
- .ci_support/win_python3.6.yaml
- recipe/meta.yaml
- recipe/post-link.sh
> version 1.7.3

- .azure-pipelines/azure-pipelines-linux.yml
- recipe/meta.yaml
> version 1.7.5

- recipe/meta.yaml
- recipe/mss_pyui_set_proj_lib_data_dir.patch
- recipe/mswms_set_proj_lib_data_dir.patch
- recipe/set_proj_lib_data_dir.patch
> patch in PROJ_LIB stuff again

- recipe/.circleci/config.yml
- recipe/.gitattributes
- recipe/.github/CONTRIBUTING.md
- recipe/.github/ISSUE_TEMPLATE.md
- recipe/.github/PULL_REQUEST_TEMPLATE.md
- recipe/.gitignore
- recipe/LICENSE.txt
- recipe/meta.yaml
> matplotlib issue fixed, 3.0.2 works

- recipe/meta.yaml
- recipe/mss_pyui_set_proj_lib_data_dir.patch
Checklist
* [] Reset the build number to `0` (if the version changed)
> fixed proj_lib path for windows installations

- recipe/meta.yaml
> fixated skyfield to >= 1.12

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-osx.yml
- .azure-pipelines/azure-pipelines-win.yml
- .ci_support/linux_python3.6.____cpython.yaml
- .ci_support/linux_python3.7.____cpython.yaml
- .ci_support/osx_python3.6.____cpython.yaml
- .ci_support/osx_python3.7.____cpython.yaml
- .ci_support/win_python3.6.____cpython.yaml
- .ci_support/win_python3.7.____cpython.yaml
- README.md
- recipe/meta.yaml
Checklist
* [-] Reset the build number to `0` (if the version changed)
> fixation of python-socketio

- recipe/meta.yaml
> fixed skipping syntax

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-osx.yml
- .azure-pipelines/azure-pipelines-win.yml
- .ci_support/linux_64_python3.9.____cpython.yaml
- .ci_support/migrations/python39.yaml
- .ci_support/osx_64_python3.9.____cpython.yaml
- .ci_support/win_64_python3.9.____cpython.yaml
- .scripts/run_docker_build.sh
- README.md
- recipe/meta.yaml
Checklist
* [X Reset the build number to `0` (if the version changed)
> try a 3.9 build

- .ci_support/linux_64_python3.6.____cpython.yaml
- .ci_support/linux_64_python3.7.____cpython.yaml
- .ci_support/linux_64_python3.8.____cpython.yaml
- .ci_support/linux_64_python3.9.____cpython.yaml
- recipe/meta.yaml
Checklist
* [X ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [-] Reset the build number to `0` (if the version changed)
> build _2 because of a change in geos we need a version below 3.9.0

- .scripts/build_steps.sh
- .scripts/logging_utils.sh
- .scripts/run_docker_build.sh
- .scripts/run_osx_build.sh
- LICENSE.txt
- README.md
- recipe/meta.yaml
> 2.0.1.1 because of fixations to sqlalchemy and sqlite

- recipe/meta.yaml
> linux build for 3.9 (missing from channel)

- recipe/meta.yaml
> build .1 fixation of pallets projects 

- recipe/meta.yaml
> added missing module

- .azure-pipelines/azure-pipelines-win.yml
- recipe/meta.yaml
> v7.0.7 build 1

- recipe/meta.yaml
> new build because pinning of pint because of new units

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-osx.yml
- .azure-pipelines/azure-pipelines-win.yml
- .gitignore
- .scripts/build_steps.sh
- .scripts/run_docker_build.sh
- .scripts/run_osx_build.sh
- .scripts/run_win_build.bat
- README.md
- recipe/meta.yaml
> build 1 because of pint upgrade

- recipe/meta.yaml
> pin fastkml to <1.0.0

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-osx.yml
- .azure-pipelines/azure-pipelines-win.yml
- .ci_support/linux_64_python3.12.____cpython.yaml
- .ci_support/osx_64_python3.12.____cpython.yaml
- .ci_support/osx_arm64_python3.12.____cpython.yaml
- .ci_support/win_64_python3.12.____cpython.yaml
- .scripts/run_win_build.bat
- README.md
- build-locally.py
- recipe/meta.yaml
> added support for py3.12
